#!/bin/bash

export SCRIPT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage() {
    echo "Usage: ./install.sh <target>"
    echo ""
    echo "Available Targets:"
    echo "ubuntu, kali-2016-2"
}

# Goals:
# - Move download-tools.sh to the install/ directory
# - Create singular installation script (choose target)
# - Make directories "smart"

INSTALL_TARGET="$1"

if [ -z "${INSTALL_TARGET}" ]; then
    echo "[Error] Please specify a target platform."
    exit 1
fi

if [ "$INSTALL_TARGET" = "--help" ]; then
    usage
    exit 0
fi

$SCRIPT_DIRECTORY/install/download-tools.sh
$SCRIPT_DIRECTORY/install/install-${INSTALL_TARGET}.sh "$SCRIPT_DIRECTORY"
